package com.supermatch.smplay.activity.RegisterActivities

import com.facebook.FacebookSdk;


import android.os.Bundle

import android.widget.Toast
import com.facebook.CallbackManager
import com.supermatch.smplay.R
import com.supermatch.smplay.activity.BaseActivities.BaseActivity
import kotlinx.android.synthetic.main.activity_select_login.*
import com.facebook.FacebookException
import com.facebook.login.LoginResult
import com.facebook.FacebookCallback
import org.jetbrains.anko.startActivity

import java.util.*
import android.content.Intent
import com.facebook.login.LoginManager



class SelectLoginActivity : BaseActivity() {


    var callbackManager : CallbackManager? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_select_login)


        initActions()


    }

    private fun initActions() {

        FacebookSdk.sdkInitialize(this.applicationContext)

        callbackManager = CallbackManager.Factory.create()

        LoginManager.getInstance().registerCallback(callbackManager,
            object : FacebookCallback<LoginResult> {
                override fun onSuccess(loginResult: LoginResult) {
                    //Add actions here

                }

                override fun onCancel() {
                    //Add actions here
                }

                override fun onError(exception: FacebookException) {

                    Toast.makeText(this@SelectLoginActivity, exception.message, Toast.LENGTH_LONG).show()
                }
            })

        btnFacebookLogin.setOnClickListener {

            LoginManager.getInstance().logInWithReadPermissions(this@SelectLoginActivity, Arrays.asList("public_profile","e-mail"));
        }


        btnEmailLogin.setOnClickListener { startActivity<LoginEmailActivity>() }
    }


    //Sets the result from facebook login to the callback manager - so we can access the token generated by facebook.
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        callbackManager?.onActivityResult(requestCode, resultCode, data)
        super.onActivityResult(requestCode, resultCode, data)
    }
}
