package com.devarthur.easyshave.activity.RegisterActivities

import com.facebook.FacebookSdk;


import android.os.Bundle

import android.widget.Toast
import com.facebook.CallbackManager
import com.devarthur.easyshave.R
import com.devarthur.easyshave.activity.BaseActivities.BaseActivity
import kotlinx.android.synthetic.main.activity_select_login.*
import com.facebook.FacebookException
import com.facebook.login.LoginResult
import com.facebook.FacebookCallback
import org.jetbrains.anko.startActivity

import android.content.Intent
import com.facebook.login.LoginManager


//This activity shows two choices for the user - Log in with e-mail details or facebook details.
//If the user login with facebook, then we ask for some aditionar information later
class SelectLoginActivity : BaseActivity() {


    var callbackManager : CallbackManager? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_select_login)


        initActions()


    }

    //Callback from facebook login sdk
    private fun initActions() {

        setupFacebookLogin()


        btnEmailLogin.setOnClickListener { startActivity<LoginEmailActivity>() }
    }

    private fun setupFacebookLogin() {

        FacebookSdk.sdkInitialize(this.applicationContext)

        callbackManager = CallbackManager.Factory.create()

        LoginManager.getInstance().registerCallback(callbackManager,
            object : FacebookCallback<LoginResult> {
                override fun onSuccess(loginResult: LoginResult) {
                    //Add actions here

                }

                override fun onCancel() {
                    //Add actions here
                }

                override fun onError(exception: FacebookException) {

                    Toast.makeText(this@SelectLoginActivity, exception.message, Toast.LENGTH_LONG).show()
                }
            })

        btnFacebookLogin.setOnClickListener {

            //Todo - remove the comment after the debug test
            //LoginManager.getInstance().logInWithReadPermissions(this@SelectLoginActivity, Arrays.asList("public_profile","e-mail"));

            //Todo - if the login with facebook was a sucess, we shoud pass the available information to the next screen - Complete profile will ask for aditional information

            startActivity<CompleteProfile>()
        }

    }


    //Sets the result from facebook login to the callback manager - so we can access the token generated by facebook.
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        callbackManager?.onActivityResult(requestCode, resultCode, data)
        super.onActivityResult(requestCode, resultCode, data)
    }
}
